#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: auth-deploy
#  labels:
#    app: auth
#    type: restapi
#spec:
#  selector:
#    matchLabels:
#      app: auth
#  replicas: 1
#  template:
#    metadata:
#      name: auth-tmpl
#      labels:
#        app: auth
#    spec:
#      containers:
#        - name: auth
#          image: ghcr.io/avickars/auth:v1
#          imagePullPolicy: Always
#          ports:
#          - name: http
#            containerPort: 3000
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: auth-svc
#spec:
#  type: LoadBalancer
#  selector:
#    app: auth
#  ports:
#  - name: http
#    protocol: "TCP"
#    port: 3000
#    targetPort: http
