apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-svc
#  labels:
#    app: playlist
spec:
  selector:
    matchLabels:
      app: playlist-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: playlist-svc
    spec:
      containers:
        - name: playlist-container
          image: ghcr.io/avickars/playlist:v1
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: playlist-svc
spec:
  selector:
    app: playlist-svc
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 6000
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: playlist-svc
  namespace: default
  annotations:
    metric-config.object.istio-requests-total.prometheus/per-replica: "true"
    metric-config.object.istio-requests-total.prometheus/query: sum(rate(istio_requests_total{destination_workload_namespace="default", destination_workload="auth-svc"}[1m]))/count(count(istio_agent_outgoing_latency{pod=~"playlist-svc.*"}) by (pod_name))
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: playlist-svc
  metrics:
    - type: Object
      object:
        metricName: istio-requests-total
        target:
          apiVersion: v1
          kind: Pod
          name: playlist-svc
        targetValue: 15