apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-svc
#  labels:
#    app: playlist
spec:
  selector:
    matchLabels:
      app: playlist-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: playlist-svc
    spec:
      containers:
        - name: playlist-container
          image: ghcr.io/avickars/playlist:v1
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: playlist-svc
spec:
  selector:
    app: playlist-svc
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 5000