apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-deploy
  labels:
    app: subscription
spec:
  selector:
    matchLabels:
      app: subscription
  replicas: 1
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: ghcr.io/avickars/subscription:v1
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-svc
spec:
  selector:
    app: subscription
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 4000
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: subscription-deploy
#  labels:
#    type: restapi
#spec:
#  selector:
#    matchLabels:
#      app: subscription
#  replicas: 1
#  template:
#    metadata:
#      name: subscription-tmpl
#      labels:
#        app: subscription
#    spec:
#      containers:
#        - name: subscription
#          image: ghcr.io/avickars/subscription:v1
#          imagePullPolicy: Always
#          ports:
#          - name: http
#            containerPort: 4000
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: subscription-svc
#spec:
#  type: LoadBalancer
#  selector:
#    app: subscription
#  ports:
#  - name: http
#    protocol: "TCP"
#    port: 4000
#    targetPort: http